on:
  workflow_dispatch:
    inputs:
      level:
        type: choice
        description: Bump level
        options:
          - patch
          - minor
          - major
          - release
          - rc
          - beta
          - alpha

name: Create release PR
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          git config user.name 'KiwiTalk Continuous Deployment'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - uses: dtolnay/rust-toolchain@stable
      
      - uses: Swatinem/rust-cache@v2

      - name: install cargo-release
        run: cargo install cargo-release

      - name: bump cargo package versions, commits
        run: |
          cargo release ${{ github.event.inputs.level }} \
            --workspace \
            --no-confirm \
            --no-tag \
            --no-push \
            --dependent-version upgrade \
            --no-publish \
            --execute

      - id: get_version
        run: |
          echo version=$(cargo metadata --format-version 1 --no-deps | \
            jq --raw-output '.packages | .[] | select(.name == "kiwi-talk-app").version') >> "$GITHUB_OUTPUT"

      - uses: peter-evans/create-pull-request@v6
        with:
          delete-branch: true
          branch: release/next
          base: dev
          labels: release
          title: Release KiwiTalk ${{ steps.get_version.outputs.version }}
          body: |
            Preparing release for KiwiTalk ${{ steps.get_version.outputs.version }}.
            This PR has been auto-generated
