name: Prettier

on:
  pull_request:
    paths:
      - '**.json'

permissions:
  pull-requests: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --dev

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --check frontend/src/assets/translations/*.json
          prettier_plugins: prettier-plugin-sort-json
          dry: true
